name: Security Pipeline

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Run Bash Hardening Script (dry)
        run: bash scripts/harden.sh || true

      - name: Run Python Vulnerability Scanner
        run: python3 scripts/vuln_scan.py
